### PR TITLE
add vuepress as doc manager

### PR DESCRIPTION
**Pull request by JuanVqz**
Issue #776 

# Solution and steps
I'm implementing [VuePress](https://vuepress.vuejs.org/) as doc manager.

1. Install VuePress as a global dependency
```sh
npm install -D VuePress
```

2. Run `npm install` inside the doc folder

3. then run the server `npm run dev`

4. Visit `http://localhost:8080/`

At this moment I am not translating the Spanish documentation because I'm only testing the links in order to see those are working correctly after we finish moving the documentation, I could start translating it.

# Checklist

- [x] Add/update/check docs (code comments and docs/ folder).
- [ ] Add/update/check tests.
- [ ] Update/check the cli generators.

# Documentation process
- [ ] Add feature 1/2/3 to the new main documentation page
- [x] Tutorials
- [x] Upgrading
- [x] Community
- [ ] api-section
- [ ] architecture
- [ ] authentication and access control
- [ ] common
- [ ] cookbook
- [ ] database
- [ ] deploy and env
- [ ] development env
- [ ] file-system
- [ ] frontend-integration
- [ ] security
- [ ] testing

NOTE: Work in progress

# Things we need to learn about VuePress
- [ ] Learn about relative routes and base path
- [ ] [Maybe we should move images, ](https://vuepress.vuejs.org/guide/assets.html)
- [ ] We need to learn how to deploy the documentation.
- [ ] [multi folder sidebar](https://github.com/shanyuhai123/vuepress-plugin-auto-sidebar#readme)

### CODE REVIEW

**Comment by JuanVqz** [comment]
screenshot_2020-12-05_17:58:55
screenshot_2020-12-05_18:00:15
screenshot_2020-12-05_18:00:23
screenshot_2020-12-05_18:00:34

**Comment by JuanVqz** [comment]
well, what do you think?

**Comment by LoicPoullain** [comment]
Thank you for sharing your interest on this. Having a better website which includes the docs, their translation and a blog is an important step in Foal's future.

This is a big project and we have to agree on the guidelines before going further in the research:

- We will presumably test both _Docusaurus_ and _Vuepress_ (in two different PRs) to see which one is the best and best meets the needs of our docs.
- Studying and migrating to the new doc system may take some weeks. In the meantime, the content of the docs might be updated. To avoid having to search which changes were made to the docs during this time, we need to not remove the existing markdown files. We will be able to move them after the test period and this will probably save us some pain.
- The actual complete translation of the documentation will be implemented in a separated PR. First, we will look at how translation works with the library with some silly examples (the navbar as you did + 1-2 example files).

**Next steps**

*The overall idea is to test the tool with some silly examples. It can be Lorem Ipsum, fake code, false translations, etc*

- [x] Add navbar with some links (Github, tutorials, etc)
- [x] Have a default welcome page
- [ ] Study how far we can edit the design of the homepage. The idea would be have this page at this end: https://foalts.org/. Is it possible?
- [x] Check that Markdown blockquoting (i.e. `> somthing`) works.
- [x] Check that syntax highlighting works with TypeScript.
- [ ] See how to implement _tabs_ like here: https://docs.foalts.org/topic-guides/authentication-and-access-control/jwt#generate-and-provide-a-secret
- [ ] Check if Markdown tables work.
- [ ] Add a blog page with two simple blog posts (two different authors).
- [ ] A translated page

Regarding the translation system, here what I think would be the best:
- The English version is the single source of truth. It's always the most up to date version.
- If a page has not been translated yet, the English page is displayed. It shouldn't be a copy. In this way, if the English page is updated, we don't have outdated English copies.
- If the English page has been updated after it was translated (let's say in Spanish), the doc framework displays a warning message on the Spanish page to tell it's not the latest version. In this way, translators and readers will know the translated page is out-of-date.

**Additional questions**

- The search with Algolia does not seem to work in the PR. Is an account required?
- Does vue press support docs versionning (ie. having a dropdown where we can select v1.x or v2.x)?
- In Gitbook and Docusaurus, we can have several dropdowns (serving different files) in the sidebar. Is it possible in vuepress?

Thank you for your work 👍

**Comment by LoicPoullain** [comment]
I studied Vuepress and Docusaurus in more detail on my side and even wrote a few pieces of code with Docusaurus.

Docusaurus seems a more mature product than Vuepress and the current prerelease version is already stable and used by many sites (create-react-app, redux, babel, algolia docsearch, etc). The framework is more adapted to build a "universal" site with a landing page, documentation and a blog. It supports versionning and the translation feature exists in the latest version (currently under test). The sidebar also natively supports sub-divisions.

That's why Docusaurus will be used for the new site and why I will close this PR. I hope you haven't spent much time working on this since my last comment.

Thank you for your research and your work on this subject. 👍

**Comment by JuanVqz** [comment]
I haven't checked anything after your last comment, glad to hear the good news!

**Pull request closed without merging**
