### PR TITLE
Fix issue #1021 to take an env var over a .env-file variable.

### PR DESCRIPTION
**Pull request by scho-to**
# Issue
When using an environment variable, which also exists in a .env file, the variable in the .env file will be used when using `Env.get()`.

# Solution and steps
I did put the code to check for process.env variables at the top of the static get-function. This way, when there is an environment variable, it is directly returned and no processing of env files needs to happen.

If there is no environment variable and no variable defined in a .env file, "undefined" is returned.

To test this, clone the repo, take the installation steps described in the .github/CONTRIBUTION.md file and run the tests.

# Checklist

- [x] Add/update/check docs (code comments and docs/ folder).
I change the text in the docs of the configuration page to match the code changes.
- [x] Add/update/check tests.
- [x] Update/check the cli generators.

### CODE REVIEW

**Comment by scho-to** [comment]
This fixes issue https://github.com/FoalTS/foal/issues/1021

**Comment by LoicPoullain** [comment]
Hi @scho-to 👋 

Thank you for taking care of this. Could you also add another test that tests that, given an environment variable is set both on the host and the `.env` file, the `get` method should return the value of the host?

**Comment by scho-to** [comment]
Hi @LoicPoullain 

i was not sure where to place the test, but I think it should be ok.

**Review by LoicPoullain — APPROVED** [review]
Looks good 👍 

I took the liberty to change the test title so that, when the test fails, we can a complete sentence in the terminal.

**Pull request merged**
