### PR TITLE
Suggest matching commands if the user mistypes

### PR DESCRIPTION
**Pull request by jamesgeorge007**
Suggests matching commands to the user utilising the [didyoumean.js](https://npmjs.com/package/didyoumean) library.

### Proposed API

`foal createa`

```bash
Usage: foal [options] [command] <command>

Options:
  -v, --version                       output the version number
  -h, --help                          output usage information

Commands:
  createapp [options] <name>          Create a new project.
  createsecret                        Create a 256-bit random secret encoded in base64.
  run|run-script <name>               Run a shell script.
  connect <framework> <path>          Configure your frontend to interact with your application.
  generate|g [options] <type> [name]  Generate and/or modify files.

  Unknown command createa.

  Did you mean createapp?
```

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
@LoicPoullain Makes sense :thinking:

**Comment by LoicPoullain** [comment]
Hi 

I’d rather not to merge untested code (as mentioned here: https://github.com/FoalTS/foal/pull/422#issuecomment-495119399) or add dependencies that are not vital (to reduce the risk of a security breach). That’s why I’m going to close this PR. Thanks anyway for your efforts!

**Comment by jamesgeorge007** [comment]
@LoicPoullain Most of the CLI tooling these days comes shipped with the command suggestion feature utilizing the respective package. Also, recently I had submitted the type definitions to `@types/didyoumean`. This has nothing to do with security breaches.

**Comment by jamesgeorge007** [comment]
@LoicPoullain FYI, Most of the CLI tooling these days comes shipped with the command suggestion feature. Also, recently I had submitted the type definitions to `@types/didyoumean`. This has nothing to do with security breaches. I think it is good to have as a new cli feature for the June release :thinking:

**Pull request closed without merging**
