### PR TITLE
add option to disable the static file serving

### PR DESCRIPTION
**Pull request by tomer-yechiel**
# Issue
can't disable serving static file
# Solution and steps

the current workaround is to create an empty folder and set the static path to that
# Checklist

- [ ] Add/update/check docs (code comments and docs/ folder).
- [ ] Add/update/check tests.
- [ ] Update/check the cli generators.

### CODE REVIEW

**Comment by tomer-yechiel** [comment]
@LoicPoullain how i can see why tests are failing?

**Comment by LoicPoullain** [comment]
Snyk checks are not public (I don't know why) but the failure is not related to this PR in this case.

Why should we add this feature? Removing the `public/` directory seems to simply works.

**Comment by tomer-yechiel** [comment]
removing the public directory does seem to work without errors.
but if I want to use Foal only as an API is I should be able to disable that feature.

**Comment by LoicPoullain** [comment]
I think that we can keep the current code as it is as it is working properly without a static folder. Let's not add extra code to maintain.

Thank you for your suggestion. 👍

**Pull request closed without merging**
