### PR TITLE
v3.0.0

### PR DESCRIPTION
**Pull request by LoicPoullain**
## Features

- [x] Drop support for Node 10 (unmaintained), 12 (not maintained from April 2022) and 14 (not maintained in less that a year). Support versions 16 and 18.
    - #1029
    - #1070
    - #1075 
- [x] Upgrade all 3p dependencies doing major upgrades (`graphql`, etc). Specify which minimum version of TypeORM is required. Upgrade the peer dependencies. 
    - #1028 
    - #1030 
    - #1033
    - #1035 
    - #1036
    - #1041 
    - #1056
    - #1148
    - #1079
    - #1081
    - #1082
    - #1154
- [x] Use latest version of AJV and use its TS integration (maybe related: #988). Check that the option names are still the same. Check potential conflicts with OpenAPI types.
    - #1037
- [x] Remove the functions `escape` and `escapeProp`. Modern frontend frameworks (React, Angular, Vue, etc) take care of this.
    - #1034 
- [x] Improve the interface of the `Context` class to mainly improve type safety.
    - #1073
- [x] Correct the bad design on the precedence of environment variables. (issue: #1021)
    - #1128
- [x] Support optional fields in @ValidateMultipartFormDataBody (issue: #1008)
    - #1048 
- [x] Support TypeORM 0.3.0.
  - #1074
  - #1089 
  - #1091
  - #1092
  - #1093
  - #1094
  - #1095
  - #1096
  - #1098
  - #1100
  - #1156
- [x] Ignore `undefined` values in configuration (issue: #1071)
  - #1113
- [x] Simplify generated CLI files.
  - #1077
- [x] ~Drop `foal generate rest-api` command.~
  - #1078
  - #1088
- [x] Make the session and JWT systems a bit simpler.
  - #1107 
  - #1108
  - #1119
  - #1133
  - #1134
  - #1135
  - #1145
  - #1147
  - #1152
- [x] Miscellaneous
  - #1114
  - #1117
  - #1121
  - #1124 
  - #1125
  - #1127
  - [Replace v2 migration with empty v3 migration](https://github.com/FoalTS/foal/pull/1031/commits/1ca888f5b68783f694ddefa817663181fdf06df3)

# Dependencies

- `@foal/aws-s3`
  - `aws-sdk` -> `@aws-sdk/client-s3@3.113.0` and `@aws-sdk/lib-storage@3.113.0`
- `@foal/cli`
  - `ajv@8.11.0`
  - `commander@9.3.0`
- `@foal/core`
  - `ajv@8.11.0`
  - `ajv-formats@2.1.1`
  - `express@4.18.1`
- `@foal/graphql`
  - `ajv@8.11.0`
  - `peerDependencies: graphql@^15.8.0`
- `@foal/jwks-rsa`
  - `jwks-rsa@2.1.4`
- `@foal/jwt`
  - `jsonwebtoken@8.5.1`
- `@foal/mongodb`
  - `mongodb@4.7.0`
- `@foal/redis`
  - `redis@4.1.0`
- `@foal/socket.io`
  - `socket.io@4.5.1`
- `@foal/storage`
  - `busboy@1.6.0`
  - `mime@3.0.0`
- `@foal/swagger`
  - `swagger-ui-dist@4.12.0`
- `@foal/typeorm`
  - `peerDependencies: typeorm@^0.3.10`
- `@foal/typestack`
  - `peerDependencies: class-transformer@0.5.1`
  - `peerDependencies: class-validator@0.13.2`

### CODE REVIEW

**Comment by LoicPoullain** [comment]
Migration guide have been written. Last things to do: update some parts of the docs + final manual check

**Comment by LoicPoullain** [comment]
Just published v3.0.0-alpha.0. We enter the manual testing phase.

**Comment by davidharting** [comment]
Thanks for all the sustained work on v3! Excited about this release!

**Comment by kingdun3284** [comment]
Thanks for the great effort !

**Comment by davidharting** [comment]
It's merged! Congrats! 🎉🎉🎉🎉🎉🎉🎉🎉

**Comment by LoicPoullain** [comment]
Thank you!

**Comment by kingdun3284** [comment]
Can't wait to try!!

**Pull request merged**
